// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DFSE
List DFSE(List& m, IntegerMatrix& table, IntegerVector& reference);
RcppExport SEXP _subgraphs_DFSE(SEXP mSEXP, SEXP tableSEXP, SEXP referenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type reference(referenceSEXP);
    rcpp_result_gen = Rcpp::wrap(DFSE(m, table, reference));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_subgraphs_DFSE", (DL_FUNC) &_subgraphs_DFSE, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_subgraphs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
